/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RbCarousel {
        "slideIntervalTime": number;
    }
    interface RbCarouselItem {
        "imageAlt"?: string;
        "imageUrl": string;
    }
}
declare global {
    interface HTMLRbCarouselElement extends Components.RbCarousel, HTMLStencilElement {
    }
    var HTMLRbCarouselElement: {
        prototype: HTMLRbCarouselElement;
        new (): HTMLRbCarouselElement;
    };
    interface HTMLRbCarouselItemElement extends Components.RbCarouselItem, HTMLStencilElement {
    }
    var HTMLRbCarouselItemElement: {
        prototype: HTMLRbCarouselItemElement;
        new (): HTMLRbCarouselItemElement;
    };
    interface HTMLElementTagNameMap {
        "rb-carousel": HTMLRbCarouselElement;
        "rb-carousel-item": HTMLRbCarouselItemElement;
    }
}
declare namespace LocalJSX {
    interface RbCarousel {
        "slideIntervalTime"?: number;
    }
    interface RbCarouselItem {
        "imageAlt"?: string;
        "imageUrl"?: string;
    }
    interface IntrinsicElements {
        "rb-carousel": RbCarousel;
        "rb-carousel-item": RbCarouselItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rb-carousel": LocalJSX.RbCarousel & JSXBase.HTMLAttributes<HTMLRbCarouselElement>;
            "rb-carousel-item": LocalJSX.RbCarouselItem & JSXBase.HTMLAttributes<HTMLRbCarouselItemElement>;
        }
    }
}
